version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: wearable_raw
      POSTGRES_USER: victor
      POSTGRES_PASSWORD: ""
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./src/wearable_pipeline/db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro

volumes:
  pgdata:
